# Inserts a blank line between shell prompts
add_newline = true

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$git_metrics\
$fill\
$cmd_duration\ 
$python\
${custom.date}\
${custom.time}\
$line_break\
$character"""

[fill]
symbol = " "

[custom.date]
command = "date +'%Y-%m-%d'"
when = true
format = "📅[$output]($style) "
style = "bright-white"

[custom.time]
command = "date +'%T'"
when = true
format = "🕙[$output]($style)"
style = "bright-white"


[python]
disabled = false
