# Inserts a blank line between shell prompts
add_newline = true

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$git_metrics\
$fill\
$cmd_duration\ 
$python\
$time\
$line_break\
$character"""

[fill]
symbol = " "

[time]
time_format = "%T"
format = "🕙 $time($style)"
style = "bright-white"
disabled = false

[python]
disabled = false