# espanso match file

# For a complete introduction, visit the official docs at: https://espanso.org/docs/

# You can use this file to define the base matches (aka snippets)
# that will be available in every application when using espanso.

# Matches are substitution rules: when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Common contractions
  - regex: "(?P<pre>^|\\s)i " # match I with a space, otherwise it will match "i" in "is" etc.
    replace: "{{pre}}I "
  - regex: "(?P<pre>^|\\s)dont\\b"
    replace: "{{pre}}don't"
  - regex: "(?P<pre>^|\\s)cant\\b"
    replace: "{{pre}}can't"
  - regex: "(?P<pre>^|\\s)wont\\b"
    replace: "{{pre}}won't"
  - regex: "(?P<pre>^|\\s)isnt\\b"
    replace: "{{pre}}isn't"
  - regex: "(?P<pre>^|\\s)arent\\b"
    replace: "{{pre}}aren't"
  - regex: "(?P<pre>^|\\s)wasnt\\b"
    replace: "{{pre}}wasn't"
  - regex: "(?P<pre>^|\\s)werent\\b"
    replace: "{{pre}}weren't"
  - regex: "(?P<pre>^|\\s)hasnt\\b"
    replace: "{{pre}}hasn't"
  - regex: "(?P<pre>^|\\s)havent\\b"
    replace: "{{pre}}haven't"
  - regex: "(?P<pre>^|\\s)hadnt\\b"
    replace: "{{pre}}hadn't"
  - regex: "(?P<pre>^|\\s)doesnt\\b"
    replace: "{{pre}}doesn't"
  - regex: "(?P<pre>^|\\s)didnt\\b"
    replace: "{{pre}}didn't"
  - regex: "(?P<pre>^|\\s)shouldnt\\b"
    replace: "{{pre}}shouldn't"
  - regex: "(?P<pre>^|\\s)wouldnt\\b"
    replace: "{{pre}}wouldn't"
  - regex: "(?P<pre>^|\\s)couldnt\\b"
    replace: "{{pre}}couldn't"
  - regex: "(?P<pre>^|\\s)mustnt\\b"
    replace: "{{pre}}mustn't"
  - regex: "(?P<pre>^|\\s)neednt\\b"
    replace: "{{pre}}needn't"
  - regex: "(?P<pre>^|\\s)oughtnt\\b"
    replace: "{{pre}}oughtn't"
  - regex: "(?P<pre>^|\\s)shant\\b"
    replace: "{{pre}}shan't"
  - regex: "(?P<pre>^|\\s)thats\\b"
    replace: "{{pre}}that's"
  - regex: "(?P<pre>^|\\s)whats\\b"
    replace: "{{pre}}what's"
  - regex: "(?P<pre>^|\\s)wheres\\b"
    replace: "{{pre}}where's"
  - regex: "(?P<pre>^|\\s)whos\\b"
    replace: "{{pre}}who's"
  - regex: "(?P<pre>^|\\s)hows\\b"
    replace: "{{pre}}how's"
  - regex: "(?P<pre>^|\\s)whens\\b"
    replace: "{{pre}}when's"
  - regex: "(?P<pre>^|\\s)whys\\b"
    replace: "{{pre}}why's"
  - regex: "(?P<pre>^|\\s)heres\\b"
    replace: "{{pre}}here's"
  - regex: "(?P<pre>^|\\s)theres\\b"
    replace: "{{pre}}there's"
  - regex: "(?P<pre>^|\\s)its\\b"
    replace: "{{pre}}it's"
  - regex: "(?P<pre>^|\\s)lets\\b"
    replace: "{{pre}}let's"
  - regex: "(?P<pre>^|\\s)hes\\b"
    replace: "{{pre}}he's"
  - regex: "(?P<pre>^|\\s)shes\\b"
    replace: "{{pre}}she's"
  - regex: "(?P<pre>^|\\s)were\\b"
    replace: "{{pre}}we're"
  - regex: "(?P<pre>^|\\s)youre\\b"
    replace: "{{pre}}you're"
  - regex: "(?P<pre>^|\\s)theyre\\b"
    replace: "{{pre}}they're"
  - regex: "(?P<pre>^|\\s)ive\\b"
    replace: "{{pre}}I've"
  - regex: "(?P<pre>^|\\s)youve\\b"
    replace: "{{pre}}you've"
  - regex: "(?P<pre>^|\\s)weve\\b"
    replace: "{{pre}}we've"
  - regex: "(?P<pre>^|\\s)theyve\\b"
    replace: "{{pre}}they've"
  - regex: "(?P<pre>^|\\s)ill\\b"
    replace: "{{pre}}I'll"
  - regex: "(?P<pre>^|\\s)youll\\b"
    replace: "{{pre}}you'll"
  - regex: "(?P<pre>^|\\s)hell\\b"
    replace: "{{pre}}he'll"
  - regex: "(?P<pre>^|\\s)shell\\b"
    replace: "{{pre}}she'll"
  - regex: "(?P<pre>^|\\s)well\\b"
    replace: "{{pre}}we'll"
  - regex: "(?P<pre>^|\\s)theyll\\b"
    replace: "{{pre}}they'll"
  - regex: "(?P<pre>^|\\s)id\\b"
    replace: "{{pre}}I'd"
  - regex: "(?P<pre>^|\\s)youd\\b"
    replace: "{{pre}}you'd"
  - regex: "(?P<pre>^|\\s)hed\\b"
    replace: "{{pre}}he'd"
  - regex: "(?P<pre>^|\\s)shed\\b"
    replace: "{{pre}}she'd"
  - regex: "(?P<pre>^|\\s)wed\\b"
    replace: "{{pre}}we'd"
  - regex: "(?P<pre>^|\\s)theyd\\b"
    replace: "{{pre}}they'd"
