# espanso match file

# For a complete introduction, visit the official docs at: https://espanso.org/docs/

# You can use this file to define the base matches (aka snippets)
# that will be available in every application when using espanso.

# Matches are substitution rules: when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  
  # Common contractions
  - regex: "\\bi "
    replace: "I "
  - regex: "\\bdont\\b"
    replace: "don't"
  - regex: "\\bcant\\b"
    replace: "can't"
  - regex: "\\bwont\\b"
    replace: "won't"
  - regex: "\\bisnt\\b"
    replace: "isn't"
  - regex: "\\barent\\b"
    replace: "aren't"
  - regex: "\\bwasnt\\b"
    replace: "wasn't"
  - regex: "\\bwerent\\b"
    replace: "weren't"
  - regex: "\\bhasnt\\b"
    replace: "hasn't"
  - regex: "\\bhavent\\b"
    replace: "haven't"
  - regex: "\\bhadnt\\b"
    replace: "hadn't"
  - regex: "\\bdoesnt\\b"
    replace: "doesn't"
  - regex: "\\bdidnt\\b"
    replace: "didn't"
  - regex: "\\bshouldnt\\b"
    replace: "shouldn't"
  - regex: "\\bwouldnt\\b"
    replace: "wouldn't"
  - regex: "\\bcouldnt\\b"
    replace: "couldn't"
  - regex: "\\bmustnt\\b"
    replace: "mustn't"
  - regex: "\\bneednt\\b"
    replace: "needn't"
  - regex: "\\boughtnt\\b"
    replace: "oughtn't"
  - regex: "\\bshant\\b"
    replace: "shan't"
  - regex: "\\bthats\\b"
    replace: "that's"
  - regex: "\\bwhats\\b"
    replace: "what's"
  - regex: "\\bwheres\\b"
    replace: "where's"
  - regex: "\\bwhos\\b"
    replace: "who's"
  - regex: "\\bhows\\b"
    replace: "how's"
  - regex: "\\bwhens\\b"
    replace: "when's"
  - regex: "\\bwhys\\b"
    replace: "why's"
  - regex: "\\bheres\\b"
    replace: "here's"
  - regex: "\\btheres\\b"
    replace: "there's"
  - regex: "\\bits\\b"
    replace: "it's"
  - regex: "\\blets\\b"
    replace: "let's"
  - regex: "\\bhes\\b"
    replace: "he's"
  - regex: "\\bshes\\b"
    replace: "she's"
  - regex: "\\bwere\\b"
    replace: "we're"
  - regex: "\\byoure\\b"
    replace: "you're"
  - regex: "\\btheyre\\b"
    replace: "they're"
  - regex: "\\bive\\b"
    replace: "I've"
  - regex: "\\byouve\\b"
    replace: "you've"
  - regex: "\\bweve\\b"
    replace: "we've"
  - regex: "\\btheyve\\b"
    replace: "they've"
  - regex: "\\bill\\b"
    replace: "I'll"
  - regex: "\\byoull\\b"
    replace: "you'll"
  - regex: "\\bhell\\b"
    replace: "he'll"
  - regex: "\\bshell\\b"
    replace: "she'll"
  - regex: "\\bwell\\b"
    replace: "we'll"
  - regex: "\\btheyll\\b"
    replace: "they'll"
  - regex: "\\bid\\b"
    replace: "I'd"
  - regex: "\\byoud\\b"
    replace: "you'd"
  - regex: "\\bhed\\b"
    replace: "he'd"
  - regex: "\\bshed\\b"
    replace: "she'd"
  - regex: "\\bwed\\b"
    replace: "we'd"
  - regex: "\\btheyd\\b"
    replace: "they'd"
