# espanso match file

# For a complete introduction, visit the official docs at: https://espanso.org/docs/

# You can use this file to define the base matches (aka snippets)
# that will be available in every application when using espanso.

# Matches are substitution rules: when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Print the current date
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"

  # Common contractions
  - regex: "(^|\\s)dont"
    replace: "don't"
  - regex: "(^|\\s)cant"
    replace: "can't"
  - regex: "(^|\\s)wont"
    replace: "won't"
  - regex: "(^|\\s)isnt"
    replace: "isn't"
  - regex: "(^|\\s)arent"
    replace: "aren't"
  - regex: "(^|\\s)wasnt"
    replace: "wasn't"
  - regex: "(^|\\s)werent"
    replace: "weren't"
  - regex: "(^|\\s)hasnt"
    replace: "hasn't"
  - regex: "(^|\\s)havent"
    replace: "haven't"
  - regex: "(^|\\s)hadnt"
    replace: "hadn't"
  - regex: "(^|\\s)doesnt"
    replace: "doesn't"
  - regex: "(^|\\s)didnt"
    replace: "didn't"
  - regex: "(^|\\s)shouldnt"
    replace: "shouldn't"
  - regex: "(^|\\s)wouldnt"
    replace: "wouldn't"
  - regex: "(^|\\s)couldnt"
    replace: "couldn't"
  - regex: "(^|\\s)mustnt"
    replace: "mustn't"
  - regex: "(^|\\s)neednt"
    replace: "needn't"
  - regex: "(^|\\s)oughtnt"
    replace: "oughtn't"
  - regex: "(^|\\s)shant"
    replace: "shan't"
  - regex: "(^|\\s)thats"
    replace: "that's"
  - regex: "(^|\\s)whats"
    replace: "what's"
  - regex: "(^|\\s)wheres"
    replace: "where's"
  - regex: "(^|\\s)whos"
    replace: "who's"
  - regex: "(^|\\s)hows"
    replace: "how's"
  - regex: "(^|\\s)whens"
    replace: "when's"
  - regex: "(^|\\s)whys"
    replace: "why's"
  - regex: "(^|\\s)heres"
    replace: "here's"
  - regex: "(^|\\s)theres"
    replace: "there's"
  - regex: "(^|\\s)its"
    replace: "it's"
  - regex: "(^|\\s)lets"
    replace: "let's"
  - regex: "(^|\\s)hes"
    replace: "he's"
  - regex: "(^|\\s)shes"
    replace: "she's"
  - regex: "(^|\\s)were"
    replace: "we're"
  - regex: "(^|\\s)youre"
    replace: "you're"
  - regex: "(^|\\s)theyre"
    replace: "they're"
  - regex: "(^|\\s)ive"
    replace: "I've"
  - regex: "(^|\\s)youve"
    replace: "you've"
  - regex: "(^|\\s)weve"
    replace: "we've"
  - regex: "(^|\\s)theyve"
    replace: "they've"
  - regex: "(^|\\s)ill"
    replace: "I'll"
  - regex: "(^|\\s)youll"
    replace: "you'll"
  - regex: "(^|\\s)hell"
    replace: "he'll"
  - regex: "(^|\\s)shell"
    replace: "she'll"
  - regex: "(^|\\s)well"
    replace: "we'll"
  - regex: "(^|\\s)theyll"
    replace: "they'll"
  - regex: "(^|\\s)id"
    replace: "I'd"
  - regex: "(^|\\s)youd"
    replace: "you'd"
  - regex: "(^|\\s)hed"
    replace: "he'd"
  - regex: "(^|\\s)shed"
    replace: "she'd"
  - regex: "(^|\\s)wed"
    replace: "we'd"
  - regex: "(^|\\s)theyd"
    replace: "they'd"
